[package]
name = "trustmebro"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.7.5", features = ["csr"] }

[dependencies.web-sys]
version = "0.3.70"
features = ["Clipboard", "Navigator"]
